// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fakwqgechuogovnhvbep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZha3dxZ2VjaHVvZ292bmh2YmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMTc2OTAsImV4cCI6MjA1NTg5MzY5MH0.rU-WSkd9fptlHODm2KLwOqhNyfcGrxgC5C65i-qZkfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);